name: foundry
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cpp-expected=1.3.1
  - expat=2.7.3
  - fmt=12.0.0
  - icu=73.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libarchive=3.8.2
  - libcurl=8.18.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmamba=2.4.0
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libsolv=0.7.35
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mamba=2.4.0
  - ncurses=6.5
  - nlohmann_json-abi=3.12.0
  - openssl=3.6.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - setuptools=80.9.0
  - simdjson=4.2.4
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - assertpy==1.1
      - asttokens==3.0.1
      - atomworks==2.2.0
      - attrs==25.4.0
      - beartype==0.22.9
      - biotite==1.4.0
      - biotraj==1.2.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - cuequivariance==0.8.1
      - cuequivariance-ops-cu12==0.8.1
      - cuequivariance-ops-torch-cu12==0.8.1
      - cuequivariance-torch==0.8.1
      - cython==3.2.4
      - cytoolz==0.12.3
      - debugpy==1.8.19
      - decorator==5.2.1
      - dm-tree==0.1.9
      - einops==0.8.1
      - einx==0.3.0
      - environs==11.2.1
      - executing==2.2.1
      - filelock==3.20.3
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - hydra-core==1.3.2
      - hydride==1.2.3
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipython-autotime==0.3.2
      - ipython-pygments-lexers==1.1.1
      - jaxtyping==0.3.6
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - loralib==0.1.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==4.2.1
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numpy==2.4.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.590.48
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==26.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py3dmol==2.5.4
      - pyarrow==17.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymol-remote==1.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rc-foundry==0.1.9
      - rdkit==2025.3.6
      - requests==2.32.5
      - rich==14.3.0
      - rootutils==1.0.7
      - scipy==1.17.0
      - sentry-sdk==2.50.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - toolz==1.1.0
      - torch==2.7.1
      - torchmetrics==1.8.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.3.1
      - typer==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uv==0.9.26
      - wadler-lindig==0.1.7
      - wandb==0.24.0
      - wcwidth==0.3.3
      - wrapt==2.0.1
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/alex/miniconda3/envs/foundry
